### ISSUE TITLE
CypressError: `cy.task('setupMetamask')` failed

### ISSUE THREAD

**Issue by blackpintz** [Synthetixio/synpress#326]
Hey, I keep getting the following error even after doing the whole setup as described in synpress readme:
```
  1) Connect metamask wallet
       "before all" hook for "visits page":
     CypressError: `cy.task('setupMetamask')` failed with the following error:

> Cannot read properties of undefined (reading 'waitForTimeout')

https://on.cypress.io/api/task

Because this error occurred during a `before all` hook we are skipping all of the remaining tests.
      at http://localhost:3000/__cypress/runner/cypress_runner.js:161147:78
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:13196:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:11131:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:11188:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:11233:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:11309:18)
      at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:7903:12)
      at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:7896:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:7912:5)
      at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:7782:14)
  From Your Spec Code:
      at Context.eval (http://localhost:3000/__cypress/tests?p=node_modules\@synthetixio\synpress\support\index.js:1036:15)

  From Node.js Internals:
    TypeError: Cannot read properties of undefined (reading 'waitForTimeout')
        at Object.initialSetup (C:\..\..\node_modules\@synthetixio\synpress\commands\metamask.js:558:37)
    at runMicrotasks (<anonymous>)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at setupMetamask (C:\..\..\node_modules\@synthetixio\synpress\plugins\index.js:211:7)
```
I run this code on package.json:  `"test:e2e": "start-server-and-test 'npm start' http-get://localhost:3000 'env-cmd -f .env synpress run'"`

Here is my spec file:

```
describe("Connect metamask wallet", () => {
    it('visits page', () => {
        cy.visit('/')
    })
})
```

I don't know if this is the issue but I am using react functional components instead of nextjs and no typescript.
Please help.

**Comment by coleUI** [comment]
@blackpintz If you want to skip metamask extension installation or metamask setup, you can use SKIP_METAMASK_INSTALL and SKIP_METAMASK_SETUP separately. Both variables accept 1 or true. 

That is from the readme. I had to use this and setup metamask with `cy.setupMetamask()` or else I would get the same error as you. 

With that said, I am still getting this error when trying to override the config file.

**Comment by blackpintz** [comment]
@coleUI, I just added a `tsconfig.json` file in the root directory and typescript packages and now the error is gone. Maybe you can also check how you are calling the test file in `package.json`. Example: `"test:synpress:open": "env-cmd -f .env synpress open"`.

**Comment by coleUI** [comment]
@blackpintz I had my tsconfig.json in the tests/e2e, but my issue was resolved when I added "supportFolder" and "pluginsFolder" in the synpress.json config file. It did not know where to reference those folders, which look in the source directory by default. I had to add values to point them to the synpress instance in node_modules.

This should probably be added to the synpress docs since it currently seems as if you can copy/paste the default values into the custom config, which is not the case

**Comment by dev2021-ctrl** [comment]
@coleUI  @blackpintz  I am facing the similar issue.I tried adding folders but still getting same error.
Please advise.
My test script is below
''''
describe('Metamask', () => {
  context('verifying commands', () => {

    it(`Try to connect to website`, () => {
      cy.visit('/');
      cy.contains('Welcome')


    });

  });
});

''''

**Comment by blackpintz** [comment]
@dev2021-ctrl Did you install the typescript packages as well? Maybe you can share more code snippets of your work...
