### ISSUE TITLE
acceptMetamaskAccess not working

### ISSUE THREAD

**Issue by tonykha123** [Synthetixio/synpress#584]
Hi there, I'm using Synpress for my dapp, and everything seems to be working properly besides the acceptMetamaskAccess(). It seems to not register that the task is done even though it has successfully been completed.
![image](https://user-images.githubusercontent.com/93644855/202312971-0eb3f24b-a285-4b44-9ced-452eb6a13013.png)

As you can see here, it has accepted the metamask access going onto the next step which is the signature request. However since the task didnt register as being completed it just times itself out and cannot proceed to the next step which is accepting the signature request.

![image](https://user-images.githubusercontent.com/93644855/202310900-7764fc72-9464-4ded-af05-5d82264e5d9e.png)

here is my code for the test case
![image](https://user-images.githubusercontent.com/93644855/202311021-b963157e-072a-42bc-bad9-5d54c6c00b0d.png)

_Originally posted by @tonykha123 in https://github.com/Synthetixio/synpress/discussions/583_

**Comment by drptbl** [comment]
Hey @tonykha123,

This issue is specifically related to SIWE.

I already know how to fix it. I will release a new version of synpress with fix in place tomorrow.

Thanks for reporting! 🙏 

I will let you know as soon as new version is out.

**Comment by drptbl** [comment]
@tonykha123 It has been fixed in `@synthetixio/synpress@3.0.4`:

To be able to connect to a dapp using SIWE, try this:
`cy.acceptMetamaskAccess({signInSignature: true})`
It will automatically accept access request and confirm signature.

If dapp doesn't use SIWE, just do `cy.acceptMetamaskAccess()`.
For any signature requests, you still want to use `cy.confirmMetamaskSignatureRequest()`.

Thanks,
Jakub.

**Comment by tonykha123** [comment]
Awesome, Thank you!

**Comment by tonykha123** [comment]
Hey Jakub, unforunately it didn't work and still returned back this error.
![image](https://user-images.githubusercontent.com/93644855/202388705-f0374483-4d0a-4ad9-b23d-7be975bcc922.png)


I managed to find out what was causing the issue and it was the fact that my metamask notifcation popup on the browser window wasnt closing after the access request. When. I removed this 'waitForEvent' in metamask.js in the node_modules folder it solved this issue . However, it seemed like this is only the case if the metamask window doesn't close after requesting access. 

![image](https://user-images.githubusercontent.com/93644855/202389234-26eed4eb-32f3-4846-bdbe-d57720309237.png)


Do you know if there's a way to make it behave like it should? , on my colleagues machine ,it seemed to be behaving properly and the test passed. However on another colleagues machine, the metamask popup window wasnt behaving as intended to how its designed in the synpress source code.

**Comment by drptbl** [comment]
> I managed to find out what was causing the issue and it was the fact that my metamask notifcation popup on the browser window wasnt closing after the access request when it goes to the signature request screen.

That's correct. I have fixed this in `@synthetixio/synpress@3.0.4`.

If you do `cy.acceptMetamaskAccess({signInSignature: true})` synpress is going to wait for navigation to signature request instead of notification close and this case should work with SIWE.

I have wrote example test here which uses `https://login.xyz`:
https://github.com/Synthetixio/synpress/blob/origin-poc/tests/e2e/specs/siwe-spec.js
You can test it out on your PC by pulling this branch and running `yarn test:e2e`.

While if you do `cy.acceptMetamaskAccess()`, synpress is going to wait for notification close instead which will throw an error with SIWE because you have additional signature request after access approval and notification doesn't close.

It seems to be weird that it works for one of you and doesn't work for another.

So, just to make sure:
1) is synpress up to date on both of your PCs (`@synthetixio/synpress@3.0.4`)?
make sure it's not cached in dependencies.
2) are you using `cy.acceptMetamaskAccess({signInSignature: true})` with SIWE?

If you're sure that there are no issues with above questions, I will need more details to be able to fix it.

3) on which machine it does work and on which machine it doesn't? can you provide more details (specs)?
4) is there any way you could provide example repository to reproduce this issue?
5) can you test out if my tests wrote for `https://login.xyz` work for you?
you can do it by pulling `origin-poc` branch from synpress repository (https://github.com/Synthetixio/synpress) => `yarn install` => `yarn test:e2e`.

Thanks for helping me out! 🙏

**Comment by tonykha123** [comment]
hey @drptbl ,
i have indeed updated synpress to 3.0.4 and confirmed that it is not cached. I have also used cy.acceptMetamaskAccess({signInSignature: true}). It still failed on the waitForEvent closed, and if i again were to remove it from the source code it would succeed.

 My colleague isn't present today but we have the same pc (2021 macbook pro m1). I should have clarified that the reason the test was working on his machine was because the metamask window was indeed closing after it was given access, whereas mines was not.

I've downloaded and ran origin poc's test and it works on my machine locally , with metamask behaving like how you intended it to in the latest release (access request then signature request in the same window). 

I also experimented and tried getting that same test that goes to https://login.xyz on my own repo and for some reason behaved differently and metamask did not ask for a signature request.  This leads me to believe that it might be something to do with my config?

I'll get back to you when my colleague replies or if i figure this out.

**Comment by tonykha123** [comment]
Hi there, seems to be resolved now. everything seemed to be working after i yarn removed @synthetixio/synpress and readded it. I also downloaded synpress and ran the test on branch origin/poc and appears to be working.


Thanks for the fix!
